wallpaper {
    monitor = desc:Dell Inc. DELL U3425WE BNR93Z3
    path = ~/.stowfiles/backgrounds/wave/wave1.jpg
    fit_mode = fill
}

wallpaper {
    monitor = desc:Shenzhen Soogeen Electronics Co. LTD. L01N8A 0x01348C5C
    path = ~/.stowfiles/backgrounds/wave/wave1.jpg
    fit_mode = cover
}

splash = false
