$font = Monospace

general {
    hide_cursor = false
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0)

    outer_color = rgba(f3bc70ee) rgba(f3bc70ee) 45deg
    check_color = rgba(f3bc70ee) rgba(f3bc70ee) 120deg
    fail_color = rgba(f3bc70ee) rgba(424c5eee) 40deg

    font_color = rgba(f3bc70ee)
    fade_on_empty = false
    rounding = 15

    font_family = $font
    placeholder_text = Input password...
    fail_text = $PAMFAIL

    dots_spacing = 0.3

    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor =
    text =  $USER
    font_size = 30
    font_family = $font
    color = rgba(f3bc70ee)

    position = 0, 100
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    font_size = 45
    font_family = $font
    color = rgba(f3bc70ee)

    position = -30, 0
    halign = right
    valign = top
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y"
    font_size = 15
    font_family = $font
    color = rgba(76859bee)

    position = -30, -150
    halign = right
    valign = top
}   

label {
    monitor =
    text = $LAYOUT[en,ru]
    font_size = 24
    onclick = hyprctl switchxkblayout all next

    position = 250, -20
    halign = center
    valign = center
}
