[opener]
edit = [{ run = 'nvim "$@"', orphan = false, block = true }]
loupe = [{ run = 'loupe "$@"', orphan = true, block = false }]
ffplay = [{ run = 'ffplay "$@"', orphan = true, block = false }]
fluidsynth = [
    { run = 'fluidsynth -a pipewire -m alsa_seq -l "$@"', orphan = false, block = true },
]
timg = [{ run = 'vimg "$@"', orphan = false, block = true }]


[open]
prepend_rules = [
    { url = "*.png", use = [
        "timg",
    ] },
    { url = "*.jpg", use = [
        "timg",
    ] },
    { url = "*.jpeg", use = [
        "timg",
    ] },
    { url = "*.gif", use = [
        "timg",
    ] },
    { url = "*.mpg", use = [
        "ffplay",
    ] },
    { url = "*.mp4", use = [
        "ffplay",
    ] },
    { url = "*.wmv", use = [
        "ffplay",
    ] },
    { url = "*.mov", use = [
        "ffplay",
    ] },
    { url = "*.avi", use = [
        "ffplay",
    ] },
    { url = "*.mid", use = [
        "fluidsynth",
    ] },
    { url = "*.midi", use = [
        "fluidsynth",
    ] },
]
